# Generated by Django 3.1.3 on 2020-12-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_auto_20201220_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photourl',
            field=models.ImageField(blank=True, default='/media/profile/blog9.jpg', null=True, upload_to='profile'),
        ),
        migrations.CreateModel(
            name='ProfilePhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='coverphotos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
