# Generated by Django 3.1.3 on 2021-01-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0007_auto_20210118_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='following',
        ),
    ]
