# Generated by Django 3.1.3 on 2020-12-01 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=500)),
                ('Pdecs', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tagsmodel',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tname', models.CharField(max_length=1000, null=True)),
                ('tdesc', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpname', models.CharField(max_length=500)),
                ('tpdecs', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('photoURL', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subComment', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commentsmodel')),
                ('scUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=1000)),
                ('overview', models.TextField(max_length=1000)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=1000)),
                ('place', models.CharField(max_length=1000)),
                ('authorname', models.CharField(default='', max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='postname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postmodel'),
        ),
    ]
