# Generated by Django 3.1.3 on 2020-12-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201201_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title_slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
