# Generated by Django 3.1.3 on 2020-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201201_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='cuser',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='c_photo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='c_userid',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='c_username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
