# Generated by Django 3.1.3 on 2020-12-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201201_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='c_photo',
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='c_username',
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='c_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
