# Generated by Django 3.1.3 on 2020-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201203_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
