# Generated by Django 3.1.3 on 2020-12-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_postmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='thumbnail',
        ),
    ]
