# Generated by Django 3.1.3 on 2020-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_postmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/'),
        ),
    ]
