# Generated by Django 3.1.3 on 2020-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201219_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnail/'),
        ),
    ]
