# Generated by Django 3.1.3 on 2020-12-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201219_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails')),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postmodel')),
            ],
        ),
    ]
