# Generated by Django 3.1.3 on 2020-12-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201220_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
