# Generated by Django 3.1.3 on 2020-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201220_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='thumbnailimage',
            field=models.ImageField(default='', upload_to='thumbnails'),
        ),
    ]
