# Generated by Django 3.1.3 on 2021-01-02 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_auto_20210102_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcommentmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcommentmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='sub_comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
