# Generated by Django 3.1.3 on 2021-01-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210108_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
