# Generated by Django 3.1.3 on 2021-01-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210118_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermodel',
        ),
    ]
